# encoding: utf-8
MM = "#{Rails.root}/app/jinda/index.mm"
DEFAULT_TITLE = 'Notes'
DEFAULT_HEADER = 'Notes'
DEFAULT_DESCRIPTION = 'Notes by Prateep Kul'
DEFAULT_KEYWORDS = %w[Notes Generated by Prateep Kul]
GMAP = false
# ADSENSE = true
NEXT = "Next >"
# comment IMAGE_LOCATION to use cloudinary (specify params in config/cloudinary.yml)
IMAGE_LOCATION = "upload"
# for debugging
DONT_SEND_MAIL = false
